### ISSUE TITLE
Sample charts not rendering under strict mode

### ISSUE THREAD

**Issue by darthtrevino** [microsoft/chart-parts#26]
https://github.com/tanduong/test-chart-parts/blob/8fde62c146c64895b991d88219d0a60994ae2123/src/components/AnotherOne.js#L41

**Comment by cedrox** [comment]
Hello, 
It appear to be the component OrdinalScale
<OrdinalScale
          name="color"
          domain="data.c"
          colorScheme={CategoricalColorScheme.category10}
        />

Thanks

**Comment by cedrox** [comment]
Hello, I try to change strict mode in tsconfig.json like this 
![image](https://user-images.githubusercontent.com/10764310/62444901-1c889500-b75f-11e9-9dad-759dc2e2a06c.png)

But it's don't work.
