### ISSUE TITLE
Link to Conference Video

### ISSUE THREAD

**Issue by curran** [Microsoft/chart-parts#30]
Newcomers to the project may benefit from having a link to [YouTube: The Missing Abstraction of Charting - Chris Trevino - React Conf 2018](https://www.youtube.com/watch?v=qqffsEHKMcM).

I personally found the video first, then found this repository.

Very interesting work!

**Comment by fabiofl** [comment]
Indeed. I found the video first too.

**Comment by darthtrevino** [comment]
Thanks guys! I posted the link to the video in the README
