### ISSUE TITLE
Future of this lib?

### ISSUE THREAD

**Issue by MrLoh** [microsoft/chart-parts#31]
I’m a big fan of the grammar of graphics and was excited to see the conference talk. But it seems like development on this project hasn’t evolved in the past two month and it certainly doesn’t seem quite finished yet.

**Comment by darthtrevino** [comment]
Thanks for the feedback! We're starting to get back into gear from the holiday break, and we definitely still have plans for this library.

In my mind, the pieces we need to address are: 
 * A better model for data transformation and filtering. Right now we're just thunking to vega's dataflow graph, but I'd like to reconsider that
 * Take a hard look at our performance, change the output model from being whole virtual-dom trees to subtree changes.
 * An approach for declarative animation.

But I'd love to hear more about what you feel is missing or could be improved! The more perspective we can gain, the better off this library will be.

**Comment by jbremmer** [comment]
I second this - got excited about this library - it's probably first one to get things right. I wish there would be more activity on this repo so it could be taken more seriously.

**Comment by kevinisaac** [comment]
I agree too. This is the best solution to building customizable graphs the right way, that I've come across. But sadly, there has been no updates for 6 months.

**Comment by darthtrevino** [comment]
My apologies, everyone. A part of this is that react-dnd can be a time vampire. My team is definitely still using this and prioritizing this in the coming months
